version = 0.1
[default.deploy.parameters]
stack_name = "resume-match"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=resume-match-jmanoj0905-ap-south-1"
